services:

  postgres-db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: quarkus-tutorial-db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - quarkus-network


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin@password
    ports:
      - '15434:80'
    depends_on:
      - postgres-db
    networks:
      - quarkus-network

networks:
  quarkus-network:
    driver: bridge